name: Build APK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Hacer ejecutable gradlew
        run: |
          touch gradlew
          chmod +x gradlew
          echo 'distributionBase=GRADLE_USER_HOME' > gradle.properties
          echo 'distributionPath=wrapper/dists' >> gradle.properties

      - name: Compilar APK
        run: |
          gradle assembleRelease --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: MiApp.apk
          path: app/build/outputs/apk/release/*.apk
